apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      containers:
      - name: cloud-app
        image: valentinasirbu/cloud-app:latest
        ports:
        - containerPort: 3000
