substitutions:
  _TAG: 'v${BUILD_ID}'

steps:
  - name: 'gradle:7.5.1-jdk17'
    entrypoint: './gradlew'
    args: ['bootJar']

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/cloud-app-vale2025/cloud-app:${_TAG}', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/cloud-app-vale2025/cloud-app:${_TAG}' ]

  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get cluster credentials
        gcloud container clusters get-credentials ${CLOUDSDK_CONTAINER_CLUSTER} \
          --zone ${CLOUDSDK_COMPUTE_ZONE}
        
        # Debug: Print current context
        kubectl config current-context
        
        # Replace tag and apply
        TAG="v${BUILD_ID}"
        sed -i "s#\${_TAG}#${TAG}#g" deployment.yaml
        cat deployment.yaml  # Debug output
        kubectl apply -f deployment.yaml
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-app-cluster'

images:
  - 'gcr.io/cloud-app-vale2025/cloud-app:${_TAG}'

options:
  logging: CLOUD_LOGGING_ONLY