apiVersion: v1
kind: Service
metadata:
  name: cloud-app-service
spec:
  type: LoadBalancer
  selector:
    app: cloud-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Change this to 8080
