substitutions:
  _TAG: 'v${BUILD_ID}'

steps:
  - name: 'gradle:7.5.1-jdk17'
    entrypoint: './gradlew'
    args: ['bootJar']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cloud-app-vale2025/cloud-app:v${BUILD_ID}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cloud-app-vale2025/cloud-app:v${BUILD_ID}']

  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed "s|\${_TAG}|v${BUILD_ID}|g" deployment.yaml | kubectl apply -f -
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-app-cluster'

images:
  - 'gcr.io/cloud-app-vale2025/cloud-app:v${BUILD_ID}'
