steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloud-app:$SHORT_SHA', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cloud-app:$SHORT_SHA']

  # Step 3: Deploy to GKE using kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/cloud-app'
      - 'cloud-app=gcr.io/$PROJECT_ID/cloud-app:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=your-gke-cluster-zone'
      - 'CLOUDSDK_CONTAINER_CLUSTER=your-gke-cluster-name'

images:
  - 'gcr.io/$PROJECT_ID/cloud-app:$SHORT_SHA'
