apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      containers:
      - name: cloud-app
        image: gcr.io/cloud-app-vale2025/cloud-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://postgres-release-postgresql:5432/mydatabase"
          - name: SPRING_DATASOURCE_USERNAME
            value: "myuser"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "mypassword"